### ISSUE TITLE
Error: error getting endorser client for channel. CouchDb instance not starting

### ISSUE THREAD

**Issue by manjinder98** [hyperledger-labs/fablo#263]
This is my current configuration but when I try to setup the network I receive the error below. Also the CouchDb instances are not starting for both peers. What could be the solution?
`Error: error getting endorser client for channel: endorser client failed to connect to peer0.org1.com:7041: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 172.18.0.5:7041: connect: connection refused"`.

```
{
  "$schema": "https://github.com/softwaremill/fablo/releases/download/0.3.0/schema.json",
  "networkSettings": {
    "fabricVersion": "2.3.2",
    "tls": true
  },
  "orgs": [
    {
      "organization": {
        "name": "Orderer",
        "domain": "orderer.com"
      },
      "orderers": [
        {
          "groupName": "group1",
          "type": "solo",
          "instances": 1
        }
      ],
      "tools": {}
    },
    {
      "organization": {
        "name": "Org1",
        "domain": "org1.com"
      },
      "peer": {
        "instances": 2,
        "db": "CouchDb"
      },
      "tools": {}
    }
  ],
  "channels": [
    {
      "name": "my-channel1",
      "orgs": [
        {
          "name": "Org1",
          "peers": [
            "peer0",
            "peer1"
          ]
        }
      ]
    }
  ],
  "chaincodes": [
    {
      "name": "chaincode1",
      "version": "0.0.1",
      "lang": "node",
      "channel": "my-channel1",
      "directory": "./chaincodes/chaincode-kv-node"
    }
  ]
}
```

**Comment by dzikowski** [comment]
Could you execute `./fablo recreate` and provide the output? Also, check if you have at least ~4-6 GB of RAM limit for Docker

**Comment by Hejwo** [comment]
Hi @manjinder98 thanks for issue.
as Jakub said it will be best to check your RAM setup for Docker and do `fablo recreate` afterwards.  
One more hint:
- It's also good to check if there are running containers using `docker ps` and shutdown them first.

If it still fails we would appreciate:  
1. Complete output of network startup visible during `fablo up`
2. Information about system:  
 - Is it MacOs/Linux/Windows
 - Your bash version `bash --version`
 - Your docker version `docker version`

**Comment by manjinder98** [comment]
Sure, this is the current output. I have checked the RAM and I have more than 6GB available for Docker, so that shouldn't be a problem.

`fablo recreate
============ \U1F916 Destroying network \U1F916 ==============
[+] Running 1/0
⠿ fablo_network_202112202033  Warning: No resource found to remove                                                                                                                                              0.0s

Removing chaincode containers & images... \U1F5D1
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
docker rm failed, Check if all fabric dockers properly was deleted
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
docker rm failed, Check if all fabric dockers properly was deleted
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
docker rm failed, Check if all fabric dockers properly was deleted
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
docker rm failed, Check if all fabric dockers properly was deleted

Removing generated configs... \U1F5D1
============ \U1F5D1 Done! Network was purged \U1F5D1 ==============
Removing /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target
Network target directory is empty
Generating network config
FABLO_VERSION:      0.3.0
FABLO_CONFIG:       /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-config.json
FABLO_NETWORK_ROOT: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target

Fablo is powered by :
_____        __ _                         ___  ____ _ _
/  ___|      / _| |                        |  \/  (_) | |
\ `--.  ___ | |_| |___      ____ _ _ __ ___| .  . |_| | |
`--. \/ _ \|  _| __\ \ /\ / / _` | '__/ _ \ |\/| | | | |
/\__/ / (_) | | | |_ \ V  V / (_| | | |  __/ |  | | | | |
\____/ \___/|_|  \__| \_/\_/ \__,_|_|  \___\_|  |_/_|_|_|
=========================================================== v: 0.3.0
Validation errors count: 0
Validation warnings count: 0
===========================================================
====== !Compatible Fablo versions found! :) =============
Compatible versions:
- 0.3.1

To update just run command:
fablo use [version]
===========================================================
Used network config: /network/workspace/../../network/fablo-config.json
Fabric version is: 2.3.2
Generating docker-compose network 'fablo_network_202112210838'...
create fabric-config/crypto-config-orderer.yaml
create fabric-config/crypto-config-org1.yaml
create fabric-config/configtx.yaml
create fabric-config/.gitignore
create fabric-docker/.env
create fabric-docker/docker-compose.yaml
create fabric-docker/channel-query-scripts.sh
create fabric-docker/commands-generated.sh
create fabric-docker.sh
create fabric-docker/scripts/cli/channel_fns.sh
create fabric-docker/scripts/base-functions.sh
create fabric-docker/scripts/channel-query-functions.sh
create fabric-docker/scripts/base-help.sh
create fabric-docker/scripts/chaincode-functions.sh
create hooks/post-generate.sh
Done & done !!! Try the network out:
-> fablo.sh up - to start network
-> fablo.sh help - to view all commands
fablo:setup-docker
Formatting generated files
Executing post-generate hook
============ \U1F913 Generating basic configs \U1F913 ==============
==== \U1F512 Generating crypto material for Orderer \U1F512 ====
Generating certs...
CONFIG_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config
CRYPTO_CONFIG_FILE_NAME: crypto-config-orderer.yaml
ORG_PATH: peerOrganizations/orderer.com
OUTPUT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/crypto-config/
FULL_CERT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/crypto-config/peerOrganizations/orderer.com

fb6d37154b77c0d883d6cb377b47af2e050048516c0c98cd1eb2cfe7250ee0e4
orderer.com
certsGenerate
==== \U1F512 Generating crypto material for Org1 \U1F512 ====
Generating certs...
CONFIG_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config
CRYPTO_CONFIG_FILE_NAME: crypto-config-org1.yaml
ORG_PATH: peerOrganizations/org1.com
OUTPUT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/crypto-config/
FULL_CERT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/crypto-config/peerOrganizations/org1.com

87b081830f721c73c2a54f7032c5315cbf7209b6e6af52a145bba4e851d8e206
org1.com
certsGenerate
==== \U1F3E0 Generating genesis block for group group1 \U1F3E0 ====
Creating genesis block...
CONFIG_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config
OUTPUT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/config
GENESIS_PROFILE_NAME: Group1Genesis
GENESIS_FILE_NAME: Group1Genesis.block

eb57d8d6c28dd386b08738ee9c0df6e205e1c3a6e8cff90dbe1ce18c0618b1c2
2021-12-21 08:38:24.482 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2021-12-21 08:38:24.540 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2021-12-21 08:38:24.540 UTC [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: fabric-config/configtx.yaml
2021-12-21 08:38:24.556 UTC [common.tools.configtxgen] doOutputBlock -> INFO 004 Generating genesis block
2021-12-21 08:38:24.556 UTC [common.tools.configtxgen] doOutputBlock -> INFO 005 Creating system channel genesis block
2021-12-21 08:38:24.562 UTC [common.tools.configtxgen] doOutputBlock -> INFO 006 Writing genesis block
genesisBlockCreate
============ \U1F680 Starting network \U1F680 ==============
[+] Running 10/10
⠿ Network fablo_network_202112210838_basic  Created                                                                                                                                                             0.0s
⠿ Container peer1.org1.com                  Started                                                                                                                                                             1.1s
⠿ Container couchdb.peer1.org1.com          Started                                                                                                                                                             0.4s
⠿ Container cli.org1.com                    Started                                                                                                                                                             0.8s
⠿ Container ca.org1.com                     Started                                                                                                                                                             1.2s
⠿ Container orderer0.group1.orderer.com     Started                                                                                                                                                             0.6s
⠿ Container ca.orderer.com                  Started                                                                                                                                                             0.8s
⠿ Container peer0.org1.com                  Started                                                                                                                                                             1.2s
⠿ Container couchdb.peer0.org1.com          Started                                                                                                                                                             0.8s
⠿ Container cli.orderer.com                 Started                                                                                                                                                             1.1s
============ \U1F913 Generating config for 'my-channel1' \U1F913 ==============
Creating channelTx for my-channel1...
CONFIG_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config
CONFIG_PROFILE: MyChannel1
OUTPUT_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/config
CHANNEL_TX_PATH: /Users/manjindermultani1998gmail.com/IdeaProjects/cs408-rosca-blockchain/fablo-target/fabric-config/config/my-channel1.tx

274d89588ca46a3e51d23975239fb391ea529c77c539a18e2750be96f22e129d
2021-12-21 08:38:31.466 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2021-12-21 08:38:31.525 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2021-12-21 08:38:31.526 UTC [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: fabric-config/configtx.yaml
2021-12-21 08:38:31.526 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Generating new channel configtx
2021-12-21 08:38:31.551 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 005 Writing new channel tx
createChannelTx
============ \U1F63B Creating 'my-channel1' on Org1/peer0 \U1F63B ==============
Creating channel with name (TLS): my-channel1
Orderer: orderer0.group1.orderer.com:7030
CORE_PEER_LOCALMSPID: Org1MSP
CORE_PEER_ADDRESS: peer0.org1.com:7041
CORE_PEER_MSPCONFIGPATH: /var/hyperledger/cli/crypto/users/Admin@org1.com/msp

TLS_CA_CERT_PATH is: /var/hyperledger/cli/crypto-orderer/tlsca.orderer.com-cert.pem
CORE_PEER_TLS_CERT_FILE: /var/hyperledger/cli/crypto/users/Admin@org1.com/tls/client.crt
CORE_PEER_TLS_KEY_FILE: /var/hyperledger/cli/crypto/users/Admin@org1.com/tls/client.key
CORE_PEER_TLS_ROOTCERT_FILE: /var/hyperledger/cli/crypto/users/Admin@org1.com/tls/ca.crt
2021-12-21 08:38:32.759 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
2021-12-21 08:38:32.879 UTC [cli.common] readBlock -> INFO 002 Received block: 0
Error: error getting endorser client for channel: endorser client failed to connect to peer0.org1.com:7041: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 172.20.0.10:7041: connect: connection refused"
`

**Comment by manjinder98** [comment]
This is what my containers look like after the command

` docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                              NAMES
e11f27ac9ac4   hyperledger/fabric-tools:2.3.2     "/bin/bash"              11 seconds ago   Up 10 seconds                                      cli.org1.com
10b1bb0668c1   hyperledger/fabric-peer:2.3.2      "peer node start"        11 seconds ago   Up 10 seconds   0.0.0.0:7042->7042/tcp, 7051/tcp   peer1.org1.com
69dc23b0ede0   hyperledger/fabric-tools:2.3.2     "/bin/bash"              11 seconds ago   Up 9 seconds                                       cli.orderer.com
2784dccecd77   hyperledger/fabric-peer:2.3.2      "peer node start"        11 seconds ago   Up 9 seconds    0.0.0.0:7041->7041/tcp, 7051/tcp   peer0.org1.com
7a4e784b0664   hyperledger/fabric-orderer:2.3.2   "orderer"                11 seconds ago   Up 9 seconds    0.0.0.0:7030->7030/tcp, 7050/tcp   orderer0.group1.orderer.com
6147b491b2a1   hyperledger/fabric-ca:1.5.0        "sh -c 'fabric-ca-se…"   11 seconds ago   Up 10 seconds   0.0.0.0:7020->7054/tcp             ca.orderer.com
5be47620cc81   hyperledger/fabric-ca:1.5.0        "sh -c 'fabric-ca-se…"   11 seconds ago   Up 10 seconds   0.0.0.0:7040->7054/tcp             ca.org1.com`

**Comment by manjinder98** [comment]
This is what my docker containers look like

<img width="970" alt="Screenshot 2021-12-21 at 09 43 35" src="https://user-images.githubusercontent.com/25366487/146899470-35cfe1fb-b5bd-429e-93db-160ee2407969.png">

**Comment by manjinder98** [comment]
This is what my docker containers look like

<img width="1225" alt="Screenshot 2021-12-21 at 09 47 04" src="https://user-images.githubusercontent.com/25366487/146899645-6c2504f0-ec61-4e54-a42e-e066db1ad5cc.png">

**Comment by manjinder98** [comment]
> 

I'm currently on Mac. My bash version is:
` bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.`

My docker version is:
`docker --version
Docker version 20.10.11, build dea9396`

**Comment by Hejwo** [comment]
Thanks - we're on it. Will let you know.

**Comment by manjinder98** [comment]
it looks like that the hyperledger fabric couch db image doesn't support arm64 but the official couch db image does support it: https://hub.docker.com/r/arm64v8/couchdb/tags. Is there a way to use the original image instead of the hyperledger one? @Hejwo  @dzikowski

**Comment by dzikowski** [comment]
You can try to workaround it with hooks. Just add at the end of your `fablo-conifg.json`:

```json
 "hooks": {
    "postGenerate": "perl -i -pe 's/hyperledger\\/fabric-couchdb:0.4.18/couchdb:3.1/g' \"./fablo-target/fabric-docker/docker-compose.yaml\""
  }
```

Then, recreate your network.

The hook will replace the CouchDB image in the generated Docker Compose file. Note: I verified the network starts on my Mac, but I'm not sure there won't be issues with chaincode execution.

**Comment by Hejwo** [comment]
@manjinder98 thanks! That was unexpected :). We've made issue for that. Our recommendations are:  
- if you just want to use Fablo you can use workaround provided by Jakub above
- we will post proper bugfix in the next release (coming soon, probably new year)

Ps. If you want to contribute feel free to grab the issue and we will explain that needs to be done. If no it's also fine and one of us will grab it shortly :)

**Comment by manjinder98** [comment]
> You can try to workaround it with hooks. Just add at the end of your `fablo-conifg.json`:
> 
> ```json
>  "hooks": {
>     "postGenerate": "perl -i -pe 's/hyperledger\\/fabric-couchdb:0.4.18/couchdb:3.1/g' \"./fablo-target/fabric-docker/docker-compose.yaml\""
>   }
> ```
> 
> Then, recreate your network.
> 
> The hook will replace the CouchDB image in the generated Docker Compose file. Note: I verified the network starts on my Mac, but I'm not sure there won't be issues with chaincode execution.

It works perfectly now. Thanks!

**Comment by manjinder98** [comment]
Sorry, I was trying to execute a query to test the network but I'm getting the same error you guys experienced with [demo](https://www.youtube.com/watch?v=WNyxB463mQI). Do you know how to solve this?
`docker exec cli.org1.com peer chaincode invoke peer0.org1.com  -C "my-channel1" -n "chaincode1" -c '{"Args":["KVContract:put", "name", "Willy Wonka"]}'
2021-12-21 11:08:49.569 UTC [chaincodeCmd] InitCmdFactory -> INFO 001 Retrieved channel (my-channel1) orderer endpoint: orderer0.group1.orderer.com:7030
Error: error getting broadcast client: orderer client failed to connect to orderer0.group1.orderer.com:7030: failed to create new connection: context deadline exceeded`

**Comment by dzikowski** [comment]
You have in your Fablo config `"tls": true`, but you don't provide path to cert in the command. You can either disable the TLS in Fablo config (`"tls": false`) or add a cert path as parameter to the command. See samples in our test scripts, for instance https://github.com/hyperledger-labs/fablo/blob/main/e2e-network/expect-invoke-cli-tls.sh calls chaincodes via cli with certs provided

**Comment by manjinder98** [comment]
Thanks a lot! Everything working fine!
Should I close this issue?

**Comment by manjinder98** [comment]
Thanks a lot! Everything working fine!
Should I close this issue?

**Comment by dzikowski** [comment]
Yes, if have no further questions, you can safely close it. We will update the CouchDB images in the #265 issue.

**Comment by Hejwo** [comment]
@manjinder98 - just wanted to say that we've realesed Fablo 1.0.0 and it contains proper bugfix for arm. And many other things.
Enjoy! :)

**Comment by manjinder98** [comment]
> @manjinder98 - just wanted to say that we've realesed Fablo 1.0.0 and it contains proper bugfix for arm. And many other things. Enjoy! :)

Hi @Hejwo, thanks very much for the update! Your team's work has really saved a lot of time setting up my project. I'll always be grateful for your tremendous work!
