### ISSUE TITLE
Fablo REST does not output responses on Chaincode Requests

### ISSUE THREAD

**Issue by lcvalves** [hyperledger-labs/fablo#277]
### The integrated [Fablo REST API](https://github.com/softwaremill/fablo-rest) does not output any responses upon making chaincode requests.

I'm using a standard WSL Terminal as well as VS Code's Thunder Client extension to make HTTP requests to the Fablo REST API endpoints.

All the requests through the authentication / users endpoints work out fine, I just can't seem to get any data to the responses when making those requests to the **Invoke** & **Query** endpoints (`{url}/invoke/:channel/:chaincode` | `{url}/query/:channel/:chaincode`)

For this example, I'm using the provided sample chaincode - [**_chaincode-kv-node_**](https://github.com/hyperledger-labs/fablo/tree/main/samples/chaincodes/chaincode-kv-node)

Here's the request through cURL:
```
curl -X POST \
  'http://localhost:8800/invoke/my-channel1/chaincode1' \
  -H 'Accept: */*' \
  -H 'User-Agent: Thunder Client (https://www.thunderclient.io)' \
  -H 'Authorization: Bearer <bearer-token>' \ //Replaced with token from Enrollment
  -H 'Content-Type: application/json' \
  -d '{
    "method": "KVContract:put",
    "args": ["key", "value"]
}'
```
Whenever I execute this command, my terminal simply stops/gets stuck until I `CTRL+C` out of it. I've checked the Fablo REST Docker Container logs and got no useful out of that other than the server is running.

Any clues on how to fix this?

**Comment by dzikowski** [comment]
Could you verify if you use valid port for Fablo REST? (check `fablo-target/fabric-docker/docker-compose.yaml` file)

Fablo REST is instantiated  per organization. For instance when you use default setup (`./fablo init`), you have two Fablo REST containers running `fablo-rest.orderer.example.com` and `fablo-rest.org1.example.com`. The first one is available on the `8800` port and the second one on `8801`.

Typically, in a common setup, the first organization (orderer org) does not have peers and cannot call chaincodes (calling chaincodes with this Fablo REST instance can cause symptoms you described). And, simultaneously, the orgranization has its own CA, so the authentication endpoints work.

So, please, try to verify the ports, and if it still fails, provide us `fablo-config.file` and we will have a closer look. If my suggestion helps, feel free to close this isse.

**Comment by lcvalves** [comment]
> Fablo REST is instantiated per organization. For instance when you use default setup (`./fablo init`), you have two Fablo REST containers running `fablo-rest.orderer.example.com` and `fablo-rest.org1.example.com`. The first one is available on the `8800` port and the second one on `8801`.

That was precisely it. I had 2 Fablo REST instances, one running on `fablo-rest.orderer.example.com` and the other one on `fablo-rest.org1.example.com`, and I was making requests to the **Orderer** one `(PORT=8800)` and should've made to the one on **Org1** `(PORT=8801)`.

Now it is working as expected, thanks for the help!

**Comment by yaswanth-12** [comment]
@dzikowski Could you please provide the link to the default setup fablo-config file? The one that gets generated from `fablo init ` doesn't contain Fablo-Rest at all.

**Comment by dzikowski** [comment]
@yaswanth-12 you should be able to init the one with Fablo REST onboard with `fablo init rest` command.

In general, to include Fablo REST for an org, you just need to provide the following code in `fablo-config.json` for the organization:

```json
  "orgs": [
    {
      "organization": { ... },
      "peer": { ... },
      "tools": {
        "fabloRest": true
      }
    },
    ...
  ],
```

Note, you need to add Fablo REST at organization level. If you need Fablo REST for orderer organization, you just need to add the config part for that organization. Fablo exposes Fablo REST instances on different ports to avoid conflicts. You can check out the target docker compose file to verify what ports you need to use for respective organizations.
