### ISSUE TITLE
Unable to run Init Node Rest instance

### ISSUE THREAD

**Issue by johnbie** [hyperledger-labs/fablo#281]
When I run `fablo init node rest` and `fablo up` on a new directory, I should be able to run the sample network. Instead, I get a `no such image: softwaremill/fablo-rest:"0.1.0": invalid reference format` error after writing the genesis block and starting network. 

I've tried it on Windows with WSL as well as with Ubuntu (via Hyper-V virtual machine on Windows), both with the docker instance running properly. I believe that there's a dependency error in the Fablo source code when accessing the fablo-rest image.

**Comment by johnbie** [comment]
I figured out that if I change the `.env` file so that the `FABLO_REST_VERSION` is equals to `0.1.0` instead of `"0.1.0"`, the process works. The same seems to be the case for `COUCHDB_VERSION` and (probably) `FABRIC_COUCHDB_VERSION`.

**Comment by johnbie** [comment]
`FABRIC_COUCHDB_VERSION` actually can be left alone.

**Comment by Hejwo** [comment]
Hi!  
Thanks for letting us know. We will fix it nearest release.  
And till that time you can try using postGenerate hooks that may automatically replace broken line.
Full fablo-config example below:
```
{
  "$schema": "https://github.com/softwaremill/fablo/releases/download/1.0.0/schema.json",
  "global": {
    "fabricVersion": "2.4.0",
    "tls": false
  },
  "hooks": {
    "postGenerate": "sed -i 's/FABRIC_COUCHDB_VERSION=\"0.4.18\"/FABRIC_COUCHDB_VERSION=0.4.18/' ./fablo-target/fabric-docker/.env"
  },
  "orgs": [
    {
      "organization": {
        "name": "Orderer",
        "domain": "orderer.example.com"
      },
      "orderers": [
        {
          "groupName": "group1",
          "type": "solo",
          "instances": 1
        }
      ],
      "tools": {}
    },
    {
      "organization": {
        "name": "Org1",
        "domain": "org1.example.com"
      },
      "peer": {
        "instances": 2,
        "db": "LevelDb"
      },
      "tools": {}
    }
  ],
  "channels": [
    {
      "name": "my-channel1",
      "orgs": [
        {
          "name": "Org1",
          "peers": [
            "peer0",
            "peer1"
          ]
        }
      ]
    }
  ],
  "chaincodes": [
    {
      "name": "chaincode1",
      "version": "0.0.1",
      "lang": "node",
      "channel": "my-channel1",
      "directory": "./chaincodes/chaincode-kv-node"
    }
  ]
}

```
