### ISSUE TITLE
CouchDb where indexes are located if using Fablo?

### ISSUE THREAD

**Issue by maciekozak** [hyperledger-labs/fablo#370]
I set the CouchDb as a peer db and want to create some indexes, but no idea where to put them.

**Comment by maciekozak** [comment]
Alright, just simple `/META-INF/statedb/couchdb/indexes/` located inside the chaincode source dir is sufficient.

**Comment by maciekozak** [comment]
Closing.

**Comment by dzikowski** [comment]
Thanks for an issue and thanks for resolving it! I didn't know that 😄
