### ISSUE TITLE
Disable CLI Nodes

### ISSUE THREAD

**Issue by txaty** [hyperledger-labs/fablo#371]
Thanks for providing such a fantastic tool!
I noticed that each organization configured will have a CLI node created.
Like for ```org1```, there will be ```cli.org2.example.com```.
Is there a way to configure the network so that the CLI nodes are not created? As sometimes we don't need them.

**Comment by dzikowski** [comment]
Unfortunately it is not possible right now since Fablo uses cli containers for some internal work, like installing channels. You can stop them manually once network is up.
