### ISSUE TITLE
Possibility to run Fabio on Apple M1

### ISSUE THREAD

**Issue by Lucas1983** [hyperledger-labs/fablo#384]
Hi,

Is it possible to provide Fabio version that is compatible with Apple M1 arm64 architecture ?
I was checking on Docker Hub and I see that currently https://hub.docker.com/r/softwaremill/fablo image supports only linux/amd64 architecture.

Regards

**Comment by dzikowski** [comment]
Hi @Lucas1983 Fablo actually works on Apple M1 (I have one and use Fablo on daily basis). Did you try? Did you have some issues with that?

**Comment by Lucas1983** [comment]
Actually it works, but while startup I constantly getting info about architecture incompatibility e.g. `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested. ` Was wondering if this has any impact ob Fabio performance ?

**Comment by Mynameisbt** [comment]
I build the fablo containers myself for ARM.  I follow these instructions:  https://www.polarsparc.com/xhtml/Hyperledger-ARM-Build.html

I am currently running 2.4.9 using this workaround https://github.com/hyperledger-labs/fablo/issues/372#issuecomment-1382080918

Following the instructions above I was able to build fabric.  I could not build fabric-ca but I am able to run successfully with fabric-ca 1.5.6.

This is my postGenerate hook:

`  "hooks": {
    "postGenerate": "perl -i -pe 's/MaxMessageCount: 10/MaxMessageCount: 1/g' \"./fablo-target/fabric-config/configtx.yaml\"; perl -i -pe 's/_VERSION=2.4.3/_VERSION=2.4.9/g' ./fablo-target/fabric-docker/.env; perl -i -pe 's/FABRIC_CA_VERSION=1.5.0/FABRIC_CA_VERSION=1.5.6/g' ./fablo-target/fabric-docker/.env;"
  }`
