### ISSUE TITLE
Asking for communication channel or email Id where I can contact you regarding  the Fablo. So, I can start contribution

### ISSUE THREAD

**Issue by Kumaravinash9** [hyperledger-labs/fablo#385]
[](url)@dzikowski How can I contact you..... Is there any communication channel or email ? So I can connect you regarding doubts while fixing issues and setting up the envioronment. Thanks.

Facing this issue when I tried to setup the fablo locally. Please help me to setup the project locally.
![fablo_local_setup_issue](https://user-images.githubusercontent.com/64456168/232890328-c969d7a0-aaba-4a08-b5b2-562ede5293a2.png)

**Comment by Vikash-8090-Yadav** [comment]
Yeah, if possible please suggest some first-time contributor issues. @dzikowski  .

**Comment by Hejwo** [comment]
Hello @Kumaravinash9 and @Vikash-8090-Yadav,

we've joined official Discord of Hyperledger Foundation [here is the invite link](https://discord.gg/hyperledger).
[and here is the Fablo channel](https://discord.com/channels/905194001349627914/1109190949394989127).  

sorry for delay!

**Comment by Hejwo** [comment]
and about you issue - to build Fablo image we use `[fablo-build.sh](https://github.com/hyperledger-labs/fablo/blob/main/fablo-build.sh)` and it's a recommended and maintained way of building images.
