### ISSUE TITLE
Remove private data v1.4 check from CI

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#396]
Our current CI uses Fabric 1.4.11 to verify private data for chaincodes. However, this test fails, because it requires obsolete version of Node (8), obsolete platform-dependent node packages, that needs to be compiled with obsolete tools. Also, last 1.4.x Fabric version has been published [over 2 years ago](https://github.com/hyperledger/fabric/releases/tag/v1.4.12).

There is no need to perform extensive tests for Fabric 1.4.x. And we should:
- [ ] Remove `test-03-private-data` check - both from CI and the whole test script
- [ ] Move private data checks to `test-02-private-data`
- [ ] Rename remaining checks, to keep naming consistent (i.e. either rename 04 to 03, or remove numbers entirely from names)
- [ ] Update `TEST_CASES.md` to reflect the updated test cases

**Comment by Sanket-0510** [comment]
hey @dzikowski feel free to assign this to me.
