### ISSUE TITLE
Create local development docs

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#436]
Include the following informations:
1. That we require DCO for commits
2. Running e2e tests (scripts)
3. Running regular integration tests
4. Updating snapshots with `npm run test:e2e-update`

**Comment by milinddethe15** [comment]
Well we have all these info at: https://github.com/hyperledger-labs/fablo/blob/main/CONTRIBUTING.md

**Comment by dzikowski** [comment]
That's true, thanks! Closing
