### ISSUE TITLE
CA URLs in connection profiles contain http even if TLS is enabled

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#437]
It should be `https`

**Comment by Sanket-0510** [comment]
Hey @dzikowski  I dug into the issue and I believe I've found a way to address it. I would like to work on this.

**Comment by dzikowski** [comment]
Great, thanks! Feel free to start.

**Comment by Sanket-0510** [comment]
> Great, thanks! Feel free to start.

Hi I have pushed the changes, can you check that out.
