### ISSUE TITLE
Emit an error where Fabric version older than 2.0 is used

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#454]
see `src/validate/index.ts`

**Comment by Akash-Singh04** [comment]
Hey is this issue still open? Would love to work on it

**Comment by dzikowski** [comment]
Sorry @Akash-Singh04 this issue is still open, but it is marked with `intern-2024` label which means it's exclusive for the Hyperledger Foundation [internship program](https://wiki.hyperledger.org/display/INTERN/Support+Hyperledger+Fabric+3+in+Fablo). And the work on that issue has already started.

**Comment by dzikowski** [comment]
I see you are currently learning GoLang, what about this one? https://github.com/hyperledger-labs/fablo/issues/99

Or something smaller: https://github.com/hyperledger-labs/fablo/issues/447

Or one of those (a bit more advanced): https://github.com/hyperledger-labs/fablo/issues/346 https://github.com/hyperledger-labs/fablo/issues/415

Also we are going to release in a week or two, so you have a change to make something that will be included in a release 🙂
