### ISSUE TITLE
Uninformative error message on invalid fablo-config.yaml

### ISSUE THREAD

**Issue by joaormatos** [hyperledger-labs/fablo#493]
Hello,

I found that having a `fablo-config.yaml` file containing an organization with a dash (`-`) in its name causes some fablo commands to fail with an uninformative error message:

```
Critical error occured:
```

Steps to reproduce:

```bash
# in an empty directory with just fablo.sh
./fablo.sh init
sed -i 's/Org1/Org-one/g' fablo-config.yaml
./fablo.sh validate
```

Expected output: a descriptive error detailing a violation of the configuration schema.

Observed output: a single like with just `Critical error occured:`

This issue is probably a symptom of a more general problem regarding validation of the configuration file.

I'm using the latest version: 2.0.0

Best regards

**Comment by dzikowski** [comment]
Diagnosed and resolved - will be released in new version. Sorry for the delay.

**Comment by dzikowski** [comment]
And you were right - it was a general issue with logging messages.
